# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19pmOSnZb2aapxu1lKLPZN7cwSa_gPSlF
"""

import numpy as np
import matplotlib.pyplot as plt

def resolver_sistema_gauss(A, b):
    """Implementação manual do método de Gauss para resolver Ax = b [cite: 19, 20]"""
    n = len(b)
    Ab = np.concatenate((A, b.reshape(n, 1)), axis=1).astype(float)

    for i in range(n):
        # Pivoteamento parcial
        max_row = np.argmax(np.abs(Ab[i:, i])) + i
        Ab[[i, max_row]] = Ab[[max_row, i]]

        # Eliminação
        for j in range(i + 1, n):
            ratio = Ab[j, i] / Ab[i, i]
            Ab[j, i:] -= ratio * Ab[i, i:]

    # Substituição regressiva
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (Ab[i, -1] - np.dot(Ab[i, i+1:n], x[i+1:n])) / Ab[i, i]
    return x

def analisar_trelica():
    # 1. ENTRADAS [cite: 9, 10, 45]
    # Treliça Warren: Nós (x, y)
    nos_coords = np.array([[0, 0], [2, 0], [1, 1.732], [4, 0]]) # N=4
    conexoes = [[0, 1], [1, 3], [0, 2], [1, 2], [2, 3]] # B=5 barras [cite: 13, 45]

    # Apoios: 0=Livre, 1=Fixo (XY), 2=Móvel (Y) [cite: 16]
    # Nó 0: Fixo, Nó 3: Móvel em X (restringe Y)
    apoios = {0: 'fixo', 3: 'movel'}

    # Cargas: 1000N vertical no nó 1 [cite: 15, 45]
    Fx = np.zeros(len(nos_coords))
    Fy = np.zeros(len(nos_coords))
    Fy[1] = -1000

    # 2. PROCESSAMENTO [cite: 17, 18]
    num_nos = len(nos_coords)
    num_barras = len(conexoes)
    # Sistema: 2N equações (equilíbrio X e Y em cada nó)
    num_eq = 2 * num_nos
    A = np.zeros((num_eq, num_barras + 3)) # Barras + 3 reações de apoio
    B_vec = np.zeros(num_eq)

    # Preencher B_vec com cargas (invertendo sinal para o outro lado da eq)
    for i in range(num_nos):
        B_vec[2*i] = -Fx[i]
        B_vec[2*i+1] = -Fy[i]

    # Montar matriz de equilíbrio
    for i, (n1, n2) in enumerate(conexoes):
        dx = nos_coords[n2][0] - nos_coords[n1][0]
        dy = nos_coords[n2][1] - nos_coords[n1][1]
        L = np.sqrt(dx**2 + dy**2)
        cos, sin = dx/L, dy/L

        # Componentes da força da barra nos nós
        A[2*n1, i], A[2*n1+1, i] = cos, sin
        A[2*n2, i], A[2*n2+1, i] = -cos, -sin

    # Adicionar reações de apoio (exemplo simplificado: Nó 0 Rx,Ry e Nó 3 Ry)
    A[0, num_barras], A[1, num_barras+1], A[2*3+1, num_barras+2] = 1, 1, 1

    # Resolver
    solucao = resolver_sistema_gauss(A, B_vec)
    forcas = solucao[:num_barras]

    # 3. SAÍDAS GRÁFICAS [cite: 23]
    fig, axs = plt.subplots(2, 2, figsize=(15, 10))

    # G1: Treliça Original [cite: 24]
    for i, (n1, n2) in enumerate(conexoes):
        x = [nos_coords[n1][0], nos_coords[n2][0]]
        y = [nos_coords[n1][1], nos_coords[n2][1]]
        axs[0,0].plot(x, y, 'go-')
        axs[0,0].text((x[0]+x[1])/2, (y[0]+y[1])/2, f'B{i}')
    axs[0,0].set_title("Treliça Original com Nós Numerados")

    # G2: Mapa de Calor (Tração/Compressão) [cite: 25, 26]
    for i, (n1, n2) in enumerate(conexoes):
        cor = 'red' if forcas[i] < -0.1 else ('blue' if forcas[i] > 0.1 else 'black')
        x = [nos_coords[n1][0], nos_coords[n2][0]]
        y = [nos_coords[n1][1], nos_coords[n2][1]]
        axs[0,1].plot(x, y, color=cor, linewidth=2)
    axs[0,1].set_title("Intensidade (Vermelho: Comp. / Azul: Tração)")

    # G3: Magnitude das Forças [cite: 27]
    axs[1,0].bar(range(num_barras), np.abs(forcas), color='skyblue')
    axs[1,0].set_title("Magnitude das Forças por Barra")
    axs[1,0].set_xticks(range(num_barras))

    # G4: Histograma [cite: 28]
    axs[1,1].hist(forcas, bins=5, color='gray', edgecolor='black')
    axs[1,1].set_title("Distribuição das Forças Internas")

    plt.tight_layout()
    plt.show()

    # Estatísticas
    print(f"Barra mais solicitada: Barra {np.argmax(np.abs(forcas))} ({max(np.abs(forcas)):.2f} N)")
    print(f"Força média: {np.mean(np.abs(forcas)):.2f} N")

analisar_trelica()
