# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19pmOSnZb2aapxu1lKLPZN7cwSa_gPSlF
"""

# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  Problema 01 – Análise de Tensões em Treliças Planas                   ║
# ║  Algoritmos e Programação – 12/05/2026                                 ║
# ║  Pronto para rodar no Google Colab                                     ║
# ╚══════════════════════════════════════════════════════════════════════════╝

# ── Instalação automática de dependências (Colab) ────────────────────────────
import subprocess, sys
for pkg in ["matplotlib", "numpy"]:
    try:
        __import__(pkg)
    except ImportError:
        subprocess.check_call([sys.executable, "-m", "pip", "install", pkg, "-q"])

import math
import random
import numpy as np                        # usado APENAS para resolver o sistema (Gauss manual abaixo)
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.colors as mcolors
import matplotlib.cm as cm
from matplotlib.gridspec import GridSpec
from copy import deepcopy

# ════════════════════════════════════════════════════════════════════════════
# 1. ELIMINAÇÃO DE GAUSS (implementação manual, sem np.linalg)
# ════════════════════════════════════════════════════════════════════════════

def gauss_jordan(A_orig, b_orig):
    """
    Resolve Ax = b pelo método de Gauss-Jordan com pivotamento parcial.
    Retorna o vetor solução x ou lança ValueError se singular.
    """
    n = len(b_orig)
    # Monta matriz aumentada [A | b]
    M = [[float(A_orig[i][j]) for j in range(n)] + [float(b_orig[i])] for i in range(n)]

    for col in range(n):
        # Pivotamento parcial
        max_row = max(range(col, n), key=lambda r: abs(M[r][col]))
        M[col], M[max_row] = M[max_row], M[col]

        pivo = M[col][col]
        if abs(pivo) < 1e-12:
            raise ValueError(f"Sistema singular na coluna {col} – verifique os apoios.")

        # Normaliza linha do pivô
        M[col] = [v / pivo for v in M[col]]

        # Elimina nas demais linhas
        for row in range(n):
            if row != col:
                fator = M[row][col]
                M[row] = [M[row][j] - fator * M[col][j] for j in range(n + 1)]

    return [M[i][n] for i in range(n)]


# ════════════════════════════════════════════════════════════════════════════
# 2. FUNÇÕES DE ENTRADA COM VALIDAÇÃO
# ════════════════════════════════════════════════════════════════════════════

def ler_int(msg, minimo=1):
    while True:
        try:
            v = int(input(msg))
            if v < minimo:
                print(f"  ✖  Deve ser >= {minimo}.")
            else:
                return v
        except ValueError:
            print("  ✖  Digite um número inteiro.")

def ler_float(msg):
    while True:
        try:
            return float(input(msg))
        except ValueError:
            print("  ✖  Digite um número real (use ponto decimal).")

def ler_apoio(msg):
    opcoes = {"livre": 0, "movel": 1, "fixo": 2, "móvel": 1}
    while True:
        v = input(msg).strip().lower()
        if v in opcoes:
            return opcoes[v]
        print("  ✖  Digite: livre | movel | fixo")


# ════════════════════════════════════════════════════════════════════════════
# 3. MONTAGEM DA MATRIZ DE EQUILÍBRIO
# ════════════════════════════════════════════════════════════════════════════

def montar_sistema(N, B, x, y, barras, Fx, Fy, apoios):
    """
    Monta a matriz de equilíbrio (2N × 2N+reações) e o vetor de cargas.
    Incógnitas: forças nas B barras + reações (Rx, Ry por fixo; Ry por móvel).
    Retorna (A, b, lista_incognitas) onde lista_incognitas descreve cada coluna.
    """
    # Identifica reações
    reacoes = []   # (nó, 'x' ou 'y')
    for i, ap in enumerate(apoios):
        if ap == 2:          # fixo: Rx e Ry
            reacoes.append((i, 'x'))
            reacoes.append((i, 'y'))
        elif ap == 1:        # móvel: só Ry
            reacoes.append((i, 'y'))

    n_inc = B + len(reacoes)   # total de incógnitas
    n_eq  = 2 * N              # equações de equilíbrio

    if n_inc != n_eq:
        raise ValueError(
            f"Sistema isostático requer {n_eq} incógnitas, mas há {n_inc}. "
            "Ajuste barras/apoios."
        )

    A = [[0.0] * n_inc for _ in range(n_eq)]
    b = [0.0] * n_eq

    # Contribuição de cada barra
    for k, (ni, nj) in enumerate(barras):
        dx = x[nj] - x[ni]
        dy = y[nj] - y[ni]
        L  = math.hypot(dx, dy)
        if L < 1e-12:
            raise ValueError(f"Barra {k} tem comprimento zero (nós {ni} e {nj} coincidem).")
        cx, cy = dx / L, dy / L

        # Equação X do nó i
        A[2*ni][k] += cx
        # Equação Y do nó i
        A[2*ni+1][k] += cy
        # Equação X do nó j (sentido oposto)
        A[2*nj][k] -= cx
        # Equação Y do nó j
        A[2*nj+1][k] -= cy

    # Contribuição das reações
    for r_idx, (ni, direcao) in enumerate(reacoes):
        col = B + r_idx
        eq  = 2*ni + (0 if direcao == 'x' else 1)
        A[eq][col] = 1.0

    # Vetor b (cargas externas, sinal negativo pois passam pro outro lado)
    for i in range(N):
        b[2*i]   = -Fx[i]
        b[2*i+1] = -Fy[i]

    incognitas = [f"F_barra{k}" for k in range(B)] + \
                 [f"R_{ni}{'x' if d=='x' else 'y'}" for ni, d in reacoes]

    return A, b, incognitas


# ════════════════════════════════════════════════════════════════════════════
# 4. CLASSIFICAÇÃO E ESTATÍSTICAS
# ════════════════════════════════════════════════════════════════════════════

def classificar(forca, tol=1e-6):
    if forca > tol:
        return "Tração (+)"
    elif forca < -tol:
        return "Compressão (−)"
    else:
        return "Nula"

def estatisticas(forcas_barras, nomes_barras):
    mags = [abs(f) for f in forcas_barras]
    idx_max = mags.index(max(mags))
    media   = sum(mags) / len(mags) if mags else 0
    print("\n" + "═"*60)
    print("  ESTATÍSTICAS")
    print("═"*60)
    print(f"  Barra mais solicitada : {nomes_barras[idx_max]}  |  {forcas_barras[idx_max]:.2f} N")
    print(f"  Força média (magnitude): {media:.2f} N")
    print(f"  Força máxima           : {max(mags):.2f} N")
    print(f"  Força mínima (não nula): {min(f for f in mags if f > 1e-6):.4f} N" if any(f > 1e-6 for f in mags) else "")
    print("═"*60)


# ════════════════════════════════════════════════════════════════════════════
# 5. GRÁFICOS
# ════════════════════════════════════════════════════════════════════════════

APOIO_LABELS = {0: "Livre", 1: "Móvel", 2: "Fixo"}
APOIO_CORES  = {0: "gray",  1: "orange", 2: "green"}

def _desenhar_apoio(ax, xi, yi, tipo, escala=0.15):
    """Desenha símbolo de apoio abaixo do nó."""
    s = escala * max(1, (max([xi]) - min([xi]) + 1))   # escala relativa
    if tipo == 2:   # fixo: triângulo preenchido + hachura
        tri = plt.Polygon([[xi, yi], [xi - s, yi - s], [xi + s, yi - s]],
                           closed=True, color="green", zorder=3, alpha=0.7)
        ax.add_patch(tri)
        ax.plot([xi - s, xi + s], [yi - s, yi - s], color="green", lw=2, zorder=4)
    elif tipo == 1: # móvel: triângulo + base com rodinhas
        tri = plt.Polygon([[xi, yi], [xi - s, yi - s], [xi + s, yi - s]],
                           closed=True, color="orange", zorder=3, alpha=0.7)
        ax.add_patch(tri)
        ax.plot([xi - s*1.1, xi + s*1.1], [yi - s - 0.05*s, yi - s - 0.05*s],
                color="orange", lw=1.5, zorder=4)

def plotar_trelica_original(N, B, x, y, barras, apoios, titulo="Treliça – geometria original"):
    fig, ax = plt.subplots(figsize=(10, 6))
    fig.patch.set_facecolor("#f8f9fa")
    ax.set_facecolor("#f8f9fa")

    # Barras
    for k, (ni, nj) in enumerate(barras):
        ax.plot([x[ni], x[nj]], [y[ni], y[nj]], 'k-', lw=2, zorder=1)
        mx, my = (x[ni]+x[nj])/2, (y[ni]+y[nj])/2
        ax.text(mx, my, f"B{k}", fontsize=8, color="#555", ha='center',
                va='center', bbox=dict(boxstyle='round,pad=0.2', fc='white', ec='none', alpha=0.7))

    # Apoios
    sx = (max(x)-min(x)+1) * 0.07
    for i, ap in enumerate(apoios):
        if ap > 0:
            _desenhar_apoio(ax, x[i], y[i], ap, escala=sx)

    # Nós
    ax.scatter(x, y, s=100, c='steelblue', zorder=5, edgecolors='white', linewidths=1.5)
    for i in range(N):
        ax.annotate(f"N{i}", (x[i], y[i]), textcoords="offset points",
                    xytext=(6, 6), fontsize=9, fontweight='bold', color='#333')

    # Legenda apoios
    patches = [mpatches.Patch(color=APOIO_CORES[t], label=APOIO_LABELS[t])
               for t in sorted(set(apoios)) if t > 0]
    if patches:
        ax.legend(handles=patches, loc='upper right', fontsize=9)

    ax.set_title(titulo, fontsize=13, fontweight='bold')
    ax.set_aspect('equal')
    ax.grid(True, ls='--', alpha=0.4)
    ax.margins(0.2)
    plt.tight_layout()
    plt.savefig("trelica_original.png", dpi=150, bbox_inches='tight')
    plt.show()
    print("  ✔  Salvo: trelica_original.png")


def plotar_mapa_calor(N, B, x, y, barras, forcas_barras):
    """Treliça colorida por intensidade: azul=tração, vermelho=compressão."""
    fig, ax = plt.subplots(figsize=(10, 6))
    fig.patch.set_facecolor("#111")
    ax.set_facecolor("#111")

    mags = [abs(f) for f in forcas_barras]
    fmax = max(mags) if max(mags) > 0 else 1

    # Colormap divergente
    cmap = plt.get_cmap("RdBu")
    norm = mcolors.Normalize(vmin=-fmax, vmax=fmax)

    for k, (ni, nj) in enumerate(barras):
        f    = forcas_barras[k]
        cor  = cmap(norm(f))
        lw   = 2 + 5 * (abs(f) / fmax)
        ax.plot([x[ni], x[nj]], [y[ni], y[nj]], color=cor, lw=lw, zorder=2, solid_capstyle='round')

    ax.scatter(x, y, s=80, c='white', zorder=5, edgecolors='#aaa', linewidths=1)
    for i in range(N):
        ax.annotate(f"N{i}", (x[i], y[i]), textcoords="offset points",
                    xytext=(5, 5), fontsize=8, color='white')

    sm = cm.ScalarMappable(cmap=cmap, norm=norm)
    sm.set_array([])
    cbar = plt.colorbar(sm, ax=ax, shrink=0.8)
    cbar.set_label("Força (N)  ←compressão | tração→", color='white', fontsize=10)
    cbar.ax.yaxis.set_tick_params(color='white')
    plt.setp(cbar.ax.yaxis.get_ticklabels(), color='white')

    ax.set_title("Mapa de calor – forças internas", fontsize=13, fontweight='bold', color='white')
    ax.set_aspect('equal')
    ax.margins(0.2)
    ax.tick_params(colors='white')
    for sp in ax.spines.values():
        sp.set_edgecolor('#444')
    plt.tight_layout()
    plt.savefig("trelica_mapa_calor.png", dpi=150, bbox_inches='tight', facecolor='#111')
    plt.show()
    print("  ✔  Salvo: trelica_mapa_calor.png")


def plotar_barras_forcas(forcas_barras, B):
    """Gráfico de barras com magnitude das forças em cada elemento."""
    fig, ax = plt.subplots(figsize=(max(8, B*0.9), 5))
    labels = [f"B{k}" for k in range(B)]
    cores  = ["#e74c3c" if f < 0 else "#3498db" if f > 0 else "#95a5a6"
              for f in forcas_barras]

    bars = ax.bar(labels, forcas_barras, color=cores, edgecolor='white', linewidth=0.5)

    # Valores sobre as barras
    for bar, v in zip(bars, forcas_barras):
        ypos = bar.get_height() + (max(abs(f) for f in forcas_barras) * 0.02) * (1 if v >= 0 else -1)
        ax.text(bar.get_x() + bar.get_width()/2, ypos, f"{v:.1f}",
                ha='center', va='bottom' if v >= 0 else 'top', fontsize=8)

    ax.axhline(0, color='black', lw=0.8)
    ax.set_xlabel("Barra", fontsize=11)
    ax.set_ylabel("Força (N)", fontsize=11)
    ax.set_title("Forças internas por elemento", fontsize=13, fontweight='bold')
    ax.grid(axis='y', ls='--', alpha=0.4)

    patch_t = mpatches.Patch(color="#3498db", label="Tração (+)")
    patch_c = mpatches.Patch(color="#e74c3c", label="Compressão (−)")
    ax.legend(handles=[patch_t, patch_c], fontsize=9)

    plt.tight_layout()
    plt.savefig("forcas_barras.png", dpi=150, bbox_inches='tight')
    plt.show()
    print("  ✔  Salvo: forcas_barras.png")


def plotar_histograma(forcas_barras):
    """Histograma da distribuição das forças internas."""
    fig, ax = plt.subplots(figsize=(8, 5))
    mags = [abs(f) for f in forcas_barras]
    bins = max(5, len(mags)//2)

    n_hist, bins_hist, patches_hist = ax.hist(mags, bins=bins,
                                               color='#9b59b6', edgecolor='white', linewidth=0.6)

    # Colore barras pelo valor
    fmax = max(mags) if mags else 1
    for patch, b in zip(patches_hist, bins_hist):
        patch.set_facecolor(plt.cm.plasma(b / fmax))

    ax.set_xlabel("Magnitude da força (N)", fontsize=11)
    ax.set_ylabel("Frequência", fontsize=11)
    ax.set_title("Distribuição das forças internas", fontsize=13, fontweight='bold')
    ax.grid(axis='y', ls='--', alpha=0.4)

    ax.axvline(sum(mags)/len(mags), color='red', lw=1.5, ls='--',
               label=f"Média: {sum(mags)/len(mags):.1f} N")
    ax.legend(fontsize=9)

    plt.tight_layout()
    plt.savefig("histograma_forcas.png", dpi=150, bbox_inches='tight')
    plt.show()
    print("  ✔  Salvo: histograma_forcas.png")


# ════════════════════════════════════════════════════════════════════════════
# 6. TRELIÇA-TESTE PADRONIZADA (Warren 4 nós, 5 barras)
# ════════════════════════════════════════════════════════════════════════════

def trelica_teste_warren():
    """
    Warren simétrica 4 nós, 5 barras.
    Nós: 0=(0,0), 1=(1,0), 2=(2,0), 3=(1,1)
    Barras: 0-1, 1-2, 0-3, 3-2, 1-3
    Carga: -1000 N no eixo Y do nó 1
    Apoio fixo no nó 0, móvel no nó 2.
    """
    N = 4
    x = [0.0, 1.0, 2.0, 1.0]
    y = [0.0, 0.0, 0.0, 1.0]
    B = 5
    barras = [(0,1),(1,2),(0,3),(3,2),(1,3)]
    Fx = [0.0, 0.0, 0.0, 0.0]
    Fy = [0.0, -1000.0, 0.0, 0.0]
    apoios = [2, 0, 1, 0]   # 0=livre,1=móvel,2=fixo
    return N, B, x, y, barras, Fx, Fy, apoios


# ════════════════════════════════════════════════════════════════════════════
# 7. GERADOR ALEATÓRIO DE TRELIÇAS (para testar N=4,8,16,32)
# ════════════════════════════════════════════════════════════════════════════

def gerar_trelica_aleatoria(N):
    """
    Gera uma treliça plana simples em grade retangular para N nós.
    Garante isostasia básica: B = 2N - 3 barras + apoios adequados.
    """
    # Distribui N nós em grade
    cols = max(2, math.ceil(math.sqrt(N)))
    rows = math.ceil(N / cols)
    x, y = [], []
    for r in range(rows):
        for c in range(cols):
            if len(x) < N:
                x.append(float(c))
                y.append(float(r))

    # Barras horizontais e verticais da grade
    barras = set()
    for i in range(N):
        ri, ci = divmod(i, cols)
        # horizontal
        if ci + 1 < cols:
            j = i + 1
            if j < N: barras.add((min(i,j), max(i,j)))
        # vertical
        if ri + 1 < rows:
            j = i + cols
            if j < N: barras.add((min(i,j), max(i,j)))
        # diagonal
        if ci + 1 < cols and ri + 1 < rows:
            j = i + cols + 1
            if j < N: barras.add((min(i,j), max(i,j)))

    barras = sorted(barras)
    B = len(barras)

    Fx = [0.0] * N
    Fy = [0.0] * N
    # Carga no nó do meio superior
    mid = N // 2
    Fy[mid] = -1000.0

    # Apoio fixo no nó 0, móvel no último nó da base
    apoios = [0] * N
    apoios[0] = 2
    # Encontra nó mais à direita na base (y=0)
    base_nos = [i for i in range(N) if abs(y[i]) < 1e-9]
    if len(base_nos) > 1:
        apoios[base_nos[-1]] = 1

    return N, B, x, y, barras, Fx, Fy, apoios


# ════════════════════════════════════════════════════════════════════════════
# 8. MODO INTERATIVO (entrada manual)
# ════════════════════════════════════════════════════════════════════════════

def modo_manual():
    print("\n" + "─"*60)
    print("  ENTRADA MANUAL")
    print("─"*60)

    N = ler_int("Número de nós N: ")
    x, y = [], []
    for i in range(N):
        print(f"  Nó {i}:")
        x.append(ler_float(f"    x[{i}]: "))
        y.append(ler_float(f"    y[{i}]: "))

    B = ler_int("Número de barras B: ")
    barras = []
    for k in range(B):
        ni = ler_int(f"  Barra {k} – nó inicial (0 a {N-1}): ", 0)
        nj = ler_int(f"  Barra {k} – nó final   (0 a {N-1}): ", 0)
        barras.append((ni, nj))

    Fx, Fy = [], []
    print("Cargas aplicadas (0 se nenhuma):")
    for i in range(N):
        Fx.append(ler_float(f"  Fx[{i}] (N): "))
        Fy.append(ler_float(f"  Fy[{i}] (N): "))

    apoios = []
    print("Tipo de apoio: livre | movel | fixo")
    for i in range(N):
        apoios.append(ler_apoio(f"  Apoio nó {i}: "))

    return N, B, x, y, barras, Fx, Fy, apoios


# ════════════════════════════════════════════════════════════════════════════
# 9. IMPRESSÃO DE RESULTADOS
# ════════════════════════════════════════════════════════════════════════════

def imprimir_resultados(forcas, incognitas, B):
    print("\n" + "═"*65)
    print("  RESULTADOS – FORÇAS INTERNAS NAS BARRAS")
    print("═"*65)
    print(f"  {'Barra':>8}  {'Força (N)':>14}  {'Classificação'}")
    print("  " + "─"*55)
    for k in range(B):
        cl = classificar(forcas[k])
        print(f"  {'B'+str(k):>8}  {forcas[k]:>14.4f}  {cl}")
    print("\n  REAÇÕES NOS APOIOS:")
    print("  " + "─"*55)
    for k in range(B, len(forcas)):
        nome = incognitas[k].replace("R_", "Reação ").replace("x", " X").replace("y", " Y")
        print(f"  {nome:>20}  {forcas[k]:>14.4f} N")
    print("═"*65)


# ════════════════════════════════════════════════════════════════════════════
# 10. PROGRAMA PRINCIPAL
# ════════════════════════════════════════════════════════════════════════════

def main():
    print("\n" + "╔" + "═"*65 + "╗")
    print("║  ANÁLISE DE TRELIÇAS PLANAS – Gauss-Jordan Manual             ║")
    print("║  Algoritmos e Programação – 12/05/2026                        ║")
    print("╚" + "═"*65 + "╝\n")

    print("Escolha o modo de entrada:")
    print("  1 – Treliça-teste padronizada (Warren 4 nós)")
    print("  2 – Treliça aleatória para N = 4, 8, 16 ou 32")
    print("  3 – Entrada manual")

    modo = ""
    while modo not in {"1","2","3"}:
        modo = input("Opção [1/2/3]: ").strip()

    if modo == "1":
        N, B, x, y, barras, Fx, Fy, apoios = trelica_teste_warren()
        print("\n  Treliça Warren 4 nós carregada.")
        print("  Resultado esperado: B0≈707N, B1≈-707N (aproximado)")

    elif modo == "2":
        N = ler_int("N (sugestão: 4, 8, 16, 32): ")
        N, B, x, y, barras, Fx, Fy, apoios = gerar_trelica_aleatoria(N)
        print(f"\n  Treliça gerada: {N} nós, {B} barras.")

    else:
        N, B, x, y, barras, Fx, Fy, apoios = modo_manual()

    # Montagem e solução
    print("\n  Montando sistema de equilíbrio...")
    try:
        A, b, incognitas = montar_sistema(N, B, x, y, barras, Fx, Fy, apoios)
    except ValueError as e:
        print(f"\n  ERRO: {e}")
        return

    print("  Resolvendo pelo método de Gauss-Jordan...")
    try:
        sol = gauss_jordan(A, b)
    except ValueError as e:
        print(f"\n  ERRO: {e}")
        return

    forcas_barras = sol[:B]
    nomes_barras  = [f"B{k}" for k in range(B)]

    # Impressão
    imprimir_resultados(sol, incognitas, B)
    estatisticas(forcas_barras, nomes_barras)

    # Somatório de reações
    rx_total = sum(sol[B+k] for k in range(len(incognitas)-B) if 'x' in incognitas[B+k])
    ry_total = sum(sol[B+k] for k in range(len(incognitas)-B) if 'y' in incognitas[B+k])
    print(f"\n  Somatório das reações: Rx = {rx_total:.2f} N  |  Ry = {ry_total:.2f} N")
    soma_fy = sum(Fy)
    print(f"  Verificação equilíbrio vertical (Ry + ΣFy = 0): {ry_total + soma_fy:.4f} N")

    # Gráficos
    print("\n  Gerando gráficos...")
    plotar_trelica_original(N, B, x, y, barras, apoios)
    plotar_mapa_calor(N, B, x, y, barras, forcas_barras)
    plotar_barras_forcas(forcas_barras, B)
    plotar_histograma(forcas_barras)

    print("\n  ✅  Análise concluída. Quatro gráficos gerados.\n")


if __name__ == "__main__":
    main()
