# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19pmOSnZb2aapxu1lKLPZN7cwSa_gPSlF
"""

import math
import matplotlib.pyplot as plt

# =====================================================
# PROBLEMA 01 - ANÁLISE DE TENSÕES EM TRELIÇAS PLANAS
# =====================================================

def gauss_jordan(A, b):
    n = len(A)

    for i in range(n):
        maior_linha = i

        for k in range(i + 1, n):
            if abs(A[k][i]) > abs(A[maior_linha][i]):
                maior_linha = k

        A[i], A[maior_linha] = A[maior_linha], A[i]
        b[i], b[maior_linha] = b[maior_linha], b[i]

        pivo = A[i][i]

        if abs(pivo) < 1e-10:
            raise ValueError("Sistema sem solução única. Verifique a treliça.")

        for j in range(n):
            A[i][j] = A[i][j] / pivo

        b[i] = b[i] / pivo

        for k in range(n):
            if k != i:
                fator = A[k][i]

                for j in range(n):
                    A[k][j] = A[k][j] - fator * A[i][j]

                b[k] = b[k] - fator * b[i]

    return b


def classificar_forca(forca):
    if forca > 1e-6:
        return "Tração"
    elif forca < -1e-6:
        return "Compressão"
    else:
        return "Nula"


def exemplo_warren():
    x = [0, 2, 1, 3]
    y = [0, 0, 1.5, 1.5]

    barras = [
        [0, 1],
        [0, 2],
        [2, 1],
        [1, 3],
        [2, 3]
    ]

    Fx = [0, 0, 0, 0]
    Fy = [0, -1000, 0, 0]

    apoios = ["fixo", "movel", "livre", "livre"]

    return x, y, barras, Fx, Fy, apoios


def montar_sistema(x, y, barras, Fx, Fy, apoios):
    N = len(x)
    B = len(barras)

    reacoes = []

    for i in range(N):
        if apoios[i] == "fixo":
            reacoes.append([i, "x"])
            reacoes.append([i, "y"])

        elif apoios[i] == "movel":
            reacoes.append([i, "y"])

    total_incognitas = B + len(reacoes)
    total_equacoes = 2 * N

    if total_incognitas != total_equacoes:
        print("Atenção: a treliça pode não ser isostática.")
        print("Equações:", total_equacoes)
        print("Incógnitas:", total_incognitas)

    A = []

    for i in range(total_equacoes):
        linha = []

        for j in range(total_incognitas):
            linha.append(0)

        A.append(linha)

    b = []

    for i in range(N):
        b.append(-Fx[i])
        b.append(-Fy[i])

    for indice_barra in range(B):
        no_i = barras[indice_barra][0]
        no_j = barras[indice_barra][1]

        dx = x[no_j] - x[no_i]
        dy = y[no_j] - y[no_i]

        comprimento = math.sqrt(dx ** 2 + dy ** 2)

        c = dx / comprimento
        s = dy / comprimento

        A[2 * no_i][indice_barra] = c
        A[2 * no_i + 1][indice_barra] = s

        A[2 * no_j][indice_barra] = -c
        A[2 * no_j + 1][indice_barra] = -s

    for k in range(len(reacoes)):
        no = reacoes[k][0]
        direcao = reacoes[k][1]

        coluna = B + k

        if direcao == "x":
            A[2 * no][coluna] = 1

        elif direcao == "y":
            A[2 * no + 1][coluna] = 1

    return A, b, reacoes


def desenhar_trelica_original(x, y, barras, apoios):
    plt.figure(figsize=(8, 5))

    for barra in barras:
        i = barra[0]
        j = barra[1]

        plt.plot([x[i], x[j]], [y[i], y[j]], 'k-o')

    for i in range(len(x)):
        plt.text(x[i], y[i] + 0.08, f"N{i}", fontsize=10)

        if apoios[i] == "fixo":
            plt.scatter(x[i], y[i], marker="s", s=120, label="Apoio fixo" if i == 0 else "")

        elif apoios[i] == "movel":
            plt.scatter(x[i], y[i], marker="^", s=120, label="Apoio móvel" if i == 1 else "")

    plt.title("Treliça Original")
    plt.xlabel("x")
    plt.ylabel("y")
    plt.grid(True)
    plt.axis("equal")
    plt.legend()
    plt.show()


def desenhar_trelica_colorida(x, y, barras, forcas):
    plt.figure(figsize=(8, 5))

    maior = max(abs(f) for f in forcas)

    if maior == 0:
        maior = 1

    for i in range(len(barras)):
        no_i = barras[i][0]
        no_j = barras[i][1]

        forca = forcas[i]

        if forca > 0:
            cor = "blue"
        elif forca < 0:
            cor = "red"
        else:
            cor = "gray"

        espessura = 1 + 4 * abs(forca) / maior

        plt.plot(
            [x[no_i], x[no_j]],
            [y[no_i], y[no_j]],
            color=cor,
            linewidth=espessura,
            marker="o"
        )

        xm = (x[no_i] + x[no_j]) / 2
        ym = (y[no_i] + y[no_j]) / 2

        plt.text(xm, ym, f"B{i}", fontsize=9)

    plt.title("Treliça Colorida por Força\nAzul = Tração | Vermelho = Compressão")
    plt.xlabel("x")
    plt.ylabel("y")
    plt.grid(True)
    plt.axis("equal")
    plt.show()


def grafico_barras_forcas(forcas):
    nomes = []

    for i in range(len(forcas)):
        nomes.append(f"B{i}")

    magnitudes = []

    for f in forcas:
        magnitudes.append(abs(f))

    plt.figure(figsize=(8, 5))
    plt.bar(nomes, magnitudes)
    plt.title("Magnitude das Forças nas Barras")
    plt.xlabel("Barras")
    plt.ylabel("Força |N|")
    plt.grid(axis="y")
    plt.show()


def histograma_forcas(forcas):
    plt.figure(figsize=(8, 5))
    plt.hist(forcas, bins=5)
    plt.title("Histograma das Forças Internas")
    plt.xlabel("Força interna")
    plt.ylabel("Frequência")
    plt.grid(True)
    plt.show()


# =====================================================
# PROGRAMA PRINCIPAL
# =====================================================

print("ANÁLISE DE TENSÕES EM TRELIÇAS PLANAS")
print("1 - Usar treliça Warren padrão")
print("2 - Digitar dados manualmente")

opcao = input("Escolha uma opção: ")

if opcao == "1":
    x, y, barras, Fx, Fy, apoios = exemplo_warren()

else:
    N = int(input("Número de nós: "))

    x = []
    y = []

    for i in range(N):
        print(f"\nNó {i}")
        x.append(float(input("Coordenada x: ")))
        y.append(float(input("Coordenada y: ")))

    B = int(input("\nNúmero de barras: "))

    barras = []

    for i in range(B):
        print(f"\nBarra {i}")
        no_i = int(input("Nó inicial: "))
        no_j = int(input("Nó final: "))

        barras.append([no_i, no_j])

    Fx = []
    Fy = []

    for i in range(N):
        print(f"\nCarga no nó {i}")
        Fx.append(float(input("Fx: ")))
        Fy.append(float(input("Fy: ")))

    apoios = []

    for i in range(N):
        print(f"\nApoio no nó {i}")
        print("Opções: livre, movel, fixo")
        apoios.append(input("Tipo de apoio: ").lower())

A, b, reacoes = montar_sistema(x, y, barras, Fx, Fy, apoios)

resultado = gauss_jordan(A, b)

B = len(barras)

forcas_barras = resultado[:B]
forcas_reacoes = resultado[B:]

# =====================================================
# TABELA DE RESULTADOS
# =====================================================

print("\nRESULTADOS DAS BARRAS")
print("-" * 60)
print(f"{'Barra':10} {'Nós':10} {'Força (N)':15} {'Classificação':15}")
print("-" * 60)

for i in range(B):
    print(f"B{i:<9} {str(barras[i]):10} {forcas_barras[i]:15.2f} {classificar_forca(forcas_barras[i]):15}")

print("\nREAÇÕES NOS APOIOS")
print("-" * 40)

for i in range(len(reacoes)):
    print(f"Nó {reacoes[i][0]} direção {reacoes[i][1]}: {forcas_reacoes[i]:.2f} N")

maior_indice = 0

for i in range(1, B):
    if abs(forcas_barras[i]) > abs(forcas_barras[maior_indice]):
        maior_indice = i

soma = 0

for f in forcas_barras:
    soma += abs(f)

media = soma / B

soma_reacoes = 0

for r in forcas_reacoes:
    soma_reacoes += r

print("\nESTATÍSTICAS")
print("-" * 40)
print(f"Barra mais solicitada: B{maior_indice}")
print(f"Força na barra mais solicitada: {forcas_barras[maior_indice]:.2f} N")
print(f"Força média absoluta: {media:.2f} N")
print(f"Somatório das reações: {soma_reacoes:.2f} N")

# =====================================================
# GRÁFICOS
# =====================================================

desenhar_trelica_original(x, y, barras, apoios)
desenhar_trelica_colorida(x, y, barras, forcas_barras)
grafico_barras_forcas(forcas_barras)
histograma_forcas(forcas_barras)
