# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1djRtCq_snvTAfnxRqNsMb4IBuxcTwtoX
"""

# Commented out IPython magic to ensure Python compatibility.
# ==========================================
# SISTEMA DE ABASTECIMENTO DE ÁGUA
# PRONTO PARA GOOGLE COLAB
# ==========================================

# %matplotlib inline

import random
import matplotlib.pyplot as plt

# LISTAS
nomes = []
demandas = []
capacidades = []
volumes = []
perdas_percentuais = []
custos_m3 = []

entregues = []
perdidos = []
custos_diarios = []
autonomias = []
riscos = []

# ==========================================
# FUNÇÕES
# ==========================================

def ler_float(texto, minimo=0):
    while True:
        try:
            valor = float(input(texto))

            if valor < minimo:
                print(f"Digite valor maior ou igual a {minimo}")
            else:
                return valor

        except:
            print("Entrada inválida")


def classificar_risco(autonomia):

    if autonomia > 3:
        return "Baixo"

    elif autonomia >= 1:
        return "Médio"

    else:
        return "Alto"


# ==========================================
# ENTRADA DE DADOS
# ==========================================

N = int(ler_float("Número de bairros: ", 1))

for i in range(N):

    print(f"\nBairro {i+1}")

    nome = input("Nome do bairro: ")

    demanda = ler_float("Demanda diária (m³): ", 0.01)

    capacidade = ler_float("Capacidade reservatório (m³): ", 0.01)

    volume = ler_float("Volume inicial (m³): ", 0)

    perda = ler_float("Perda tubulação (%): ", 0)

    custo = ler_float("Custo bombeamento por m³: ", 0)

    if volume > capacidade:
        volume = capacidade

    nomes.append(nome)
    demandas.append(demanda)
    capacidades.append(capacidade)
    volumes.append(volume)
    perdas_percentuais.append(perda)
    custos_m3.append(custo)

# ==========================================
# PROCESSAMENTO
# ==========================================

for i in range(N):

    volume_perdido = demandas[i] * perdas_percentuais[i] / 100

    volume_entregue = demandas[i] - volume_perdido

    custo_diario = demandas[i] * custos_m3[i]

    autonomia = volumes[i] / demandas[i]

    risco = classificar_risco(autonomia)

    perdidos.append(volume_perdido)
    entregues.append(volume_entregue)
    custos_diarios.append(custo_diario)
    autonomias.append(autonomia)
    riscos.append(risco)

# ==========================================
# TABELA
# ==========================================

print("\nRESULTADOS")
print("-" * 100)

print(f"{'Bairro':15} {'Demanda':10} {'Entregue':10} {'Perdido':10} {'Custo':10} {'Autonomia':12} {'Risco':10}")

print("-" * 100)

for i in range(N):

    print(f"{nomes[i]:15} "
          f"{demandas[i]:10.2f} "
          f"{entregues[i]:10.2f} "
          f"{perdidos[i]:10.2f} "
          f"{custos_diarios[i]:10.2f} "
          f"{autonomias[i]:12.2f} "
          f"{riscos[i]:10}")

# ==========================================
# BAIRRO MAIS CRÍTICO
# ==========================================

indice_critico = autonomias.index(min(autonomias))

print(f"\nBairro mais crítico: {nomes[indice_critico]}")

# ==========================================
# GRÁFICO 1
# DEMANDA X ENTREGA
# ==========================================

plt.figure(figsize=(8,5))

plt.bar(nomes, demandas, label="Demanda")

plt.bar(nomes, entregues, label="Entregue")

plt.title("Demanda x Volume Entregue")

plt.xlabel("Bairros")

plt.ylabel("Volume (m³)")

plt.legend()

plt.xticks(rotation=45)

plt.show()

# ==========================================
# GRÁFICO 2
# CUSTOS
# ==========================================

plt.figure(figsize=(8,5))

plt.bar(nomes, custos_diarios)

plt.title("Custo Diário por Bairro")

plt.xlabel("Bairros")

plt.ylabel("Custo (R$)")

plt.xticks(rotation=45)

plt.show()

# ==========================================
# GRÁFICO 3
# RISCOS
# ==========================================

contagem = {
    "Baixo": riscos.count("Baixo"),
    "Médio": riscos.count("Médio"),
    "Alto": riscos.count("Alto")
}

plt.figure(figsize=(6,5))

plt.bar(contagem.keys(), contagem.values())

plt.title("Distribuição dos Riscos")

plt.xlabel("Nível de risco")

plt.ylabel("Quantidade")

plt.show()

# ==========================================
# SIMULAÇÃO DE 7 DIAS
# ==========================================

historico = [[volumes[i]] for i in range(N)]

volumes_simulados = volumes.copy()

print("\nSIMULAÇÃO DE 7 DIAS")
print("-" * 60)

for dia in range(1, 8):

    print(f"\nDia {dia}")

    for i in range(N):

        variacao = random.uniform(0.8, 1.2)

        demanda_dia = demandas[i] * variacao

        volumes_simulados[i] -= demanda_dia

        if volumes_simulados[i] < 0:
            volumes_simulados[i] = 0

        historico[i].append(volumes_simulados[i])

        autonomia = volumes_simulados[i] / demandas[i]

        risco = classificar_risco(autonomia)

        print(f"{nomes[i]} | "
              f"Demanda: {demanda_dia:.2f} | "
              f"Volume: {volumes_simulados[i]:.2f} | "
              f"Risco: {risco}")

        if risco == "Alto":
            print(f"{nomes[i]} entrou em situação crítica.")

# ==========================================
# GRÁFICO 4
# EVOLUÇÃO DOS RESERVATÓRIOS
# ==========================================

dias = list(range(8))

plt.figure(figsize=(8,5))

for i in range(N):

    plt.plot(dias,
             historico[i],
             marker='o',
             label=nomes[i])

plt.title("Evolução dos Reservatórios")

plt.xlabel("Dias")

plt.ylabel("Volume disponível (m³)")

plt.legend()

plt.grid(True)

plt.show()
